#!/bin/bash

DOT_CFG=${PWD}/.configure

source ${DOT_CFG}
echo "" > ${DOT_CFG}

if [ "$1" == "arch" ]
then
	if [ "$2" == "3602" ]
	then FAINT_PLATFORM="3602"
	elif [ "$2" == "5602" ]
	then FAINT_PLATFORM="5602"
	elif [ "$2" == "marvell" ]
	then FAINT_PLATFORM="marvell"
	elif [ "$2" == "x86" ]
	then FAINT_PLATFORM="x86"
	fi
elif [ "$1" == "debug" ]
then
	if [ "$2" == "yes" ]
	then FAINT_DEBUG="yes"
	elif [ "$2" == "no" ]
	then FAINT_DEBUG="no"
	fi
fi

echo "export X86_OCTEON_SDK_ROOT=${X86_OCTEON_SDK_ROOT}"  >> ${DOT_CFG}
echo "export X86_CAVIUM_SRC_ROOT=${X86_CAVIUM_SRC_ROOT}" >> ${DOT_CFG}
echo "export X86_LINUX_KERNEL=${X86_LINUX_KERNEL}" >> ${DOT_CFG}
echo "export X86_LINUX_SRC=${X86_LINUX_SRC}" >> ${DOT_CFG}
echo "export X86_GCC_PATH=${X86_GCC_PATH}" >> ${DOT_CFG}
echo "export X86_GCC_INCDIR=${X86_GCC_INCDIR}" >> ${DOT_CFG}
echo "export X86_GCC_LIBDIR=${X86_GCC_LIBDIR}" >> ${DOT_CFG}
echo "export X86_IMG_FS_ROOT=${X86_IMG_FS_ROOT}" >> ${DOT_CFG}
echo "export X86_IMG_MK_ROOT=${X86_IMG_MK_ROOT}" >> ${DOT_CFG}
echo "export X86_IMG_MK_TARGET=${X86_IMG_MK_TARGET}" >> ${DOT_CFG}
echo "export X86_IMG_MK_OUTPUT=${X86_IMG_MK_OUTPUT}" >> ${DOT_CFG}
echo "" >> ${DOT_CFG}

echo "export MV_88DE3010_OCTEON_SDK_ROOT=${MV_88DE3010_OCTEON_SDK_ROOT}"  >> ${DOT_CFG}
echo "export MV_88DE3010_CAVIUM_SRC_ROOT=${MV_88DE3010_CAVIUM_SRC_ROOT}" >> ${DOT_CFG}
echo "export MV_88DE3010_LINUX_KERNEL=${MV_88DE3010_LINUX_KERNEL}" >> ${DOT_CFG}
echo "export MV_88DE3010_LINUX_SRC=${MV_88DE3010_LINUX_SRC}" >> ${DOT_CFG}
echo "export MV_88DE3010_GCC_PATH=${MV_88DE3010_GCC_PATH}" >> ${DOT_CFG}
echo "export MV_88DE3010_GCC_INCDIR=${MV_88DE3010_GCC_INCDIR}" >> ${DOT_CFG}
echo "export MV_88DE3010_GCC_LIBDIR=${MV_88DE3010_GCC_LIBDIR}" >> ${DOT_CFG}
echo "export MV_88DE3010_IMG_FS_ROOT=${MV_88DE3010_IMG_FS_ROOT}" >> ${DOT_CFG}
echo "export MV_88DE3010_IMG_MK_ROOT=${MV_88DE3010_IMG_MK_ROOT}" >> ${DOT_CFG}
echo "export MV_88DE3010_IMG_MK_TARGET=${MV_88DE3010_IMG_MK_TARGET}" >> ${DOT_CFG}
echo "export MV_88DE3010_IMG_MK_OUTPUT=${MV_88DE3010_IMG_MK_OUTPUT}" >> ${DOT_CFG}
echo "" >> ${DOT_CFG}

echo "export CVM_5602_OCTEON_SDK_ROOT=${CVM_5602_OCTEON_SDK_ROOT}"  >> ${DOT_CFG}
echo "export CVM_5602_CAVIUM_SRC_ROOT=${CVM_5602_CAVIUM_SRC_ROOT}" >> ${DOT_CFG}
echo "export CVM_5602_LINUX_KERNEL=${CVM_5602_LINUX_KERNEL}" >> ${DOT_CFG}
echo "export CVM_5602_LINUX_SRC=${CVM_5602_LINUX_SRC}" >> ${DOT_CFG}
echo "export CVM_5602_GCC_PATH=${CVM_5602_GCC_PATH}" >> ${DOT_CFG}
echo "export CVM_5602_GCC_INCDIR=${CVM_5602_GCC_INCDIR}" >> ${DOT_CFG}
echo "export CVM_5602_GCC_LIBDIR=${CVM_5602_GCC_LIBDIR}" >> ${DOT_CFG}
echo "export CVM_5602_IMG_FS_ROOT=${CVM_5602_IMG_FS_ROOT}" >> ${DOT_CFG}
echo "export CVM_5602_IMG_MK_ROOT=${CVM_5602_IMG_MK_ROOT}" >> ${DOT_CFG}
echo "export CVM_5602_IMG_MK_TARGET=${CVM_5602_IMG_MK_TARGET}" >> ${DOT_CFG}
echo "export CVM_5602_IMG_MK_OUTPUT=${CVM_5602_IMG_MK_OUTPUT}" >> ${DOT_CFG}
echo "" >> ${DOT_CFG}

echo "export CVM_3602_OCTEON_SDK_ROOT=${CVM_3602_OCTEON_SDK_ROOT}"  >> ${DOT_CFG}
echo "export CVM_3602_CAVIUM_SRC_ROOT=${CVM_3602_CAVIUM_SRC_ROOT}" >> ${DOT_CFG}
echo "export CVM_3602_LINUX_KERNEL=${CVM_3602_LINUX_KERNEL}" >> ${DOT_CFG}
echo "export CVM_3602_LINUX_SRC=${CVM_3602_LINUX_SRC}" >> ${DOT_CFG}
echo "export CVM_3602_GCC_PATH=${CVM_3602_GCC_PATH}" >> ${DOT_CFG}
echo "export CVM_3602_GCC_INCDIR=${CVM_3602_GCC_INCDIR}" >> ${DOT_CFG}
echo "export CVM_3602_GCC_LIBDIR=${CVM_3602_GCC_LIBDIR}" >> ${DOT_CFG}
echo "export CVM_3602_IMG_FS_ROOT=${CVM_3602_IMG_FS_ROOT}" >> ${DOT_CFG}
echo "export CVM_3602_IMG_MK_ROOT=${CVM_3602_IMG_MK_ROOT}" >> ${DOT_CFG}
echo "export CVM_3602_IMG_MK_TARGET=${CVM_3602_IMG_MK_TARGET}" >> ${DOT_CFG}
echo "export CVM_3602_IMG_MK_OUTPUT=${CVM_3602_IMG_MK_OUTPUT}" >> ${DOT_CFG}
echo "" >> ${DOT_CFG}

echo "" >> ${DOT_CFG}

echo "" >> ${DOT_CFG}
echo "export FAINT_PLATFORM=${FAINT_PLATFORM}" >> ${DOT_CFG}
echo "export FAINT_DEBUG=${FAINT_DEBUG}" >> ${DOT_CFG}

if [ "${FAINT_PLATFORM}" == "3602" ]
then
	echo "" >> ${DOT_CFG}
	echo "export GCC_INCDIR=${CVM_3602_GCC_INCDIR}"  >> ${DOT_CFG}
	echo "export GCC_LIBDIR=${CVM_3602_GCC_LIBDIR}"  >> ${DOT_CFG}
	echo "export IMG_FS_ROOT=${CVM_3602_IMG_FS_ROOT}"  >> ${DOT_CFG}
	echo "export IMG_MK_ROOT=${CVM_3602_IMG_MK_ROOT}"  >> ${DOT_CFG}
	echo "export IMG_MK_TARGET=${CVM_3602_IMG_MK_TARGET}"  >> ${DOT_CFG}
	echo "export IMG_MK_OUTPUT=${CVM_3602_IMG_MK_OUTPUT}"  >> ${DOT_CFG}
	echo "" >> ${DOT_CFG}
	echo "export OCTEON_SDK_ROOT=${CVM_3602_OCTEON_SDK_ROOT}"  >> ${DOT_CFG}
	echo "export CAVIUM_SRC_ROOT=${CVM_3602_CAVIUM_SRC_ROOT}" >> ${DOT_CFG}
	echo "export CLOUD_PRJ_ROOT=`pwd`" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	echo "export LINUX_KERNEL=${CVM_3602_LINUX_KERNEL}" >> ${DOT_CFG}
	echo "export LINUX_SRC=${CVM_3602_LINUX_SRC}" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	echo "export WWARCH=Octeon" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	echo "export VAIL_SRC=${CVM_3602_CAVIUM_SRC_ROOT}/vail" >> ${DOT_CFG}
	echo "export WWK=${CVM_3602_CAVIUM_SRC_ROOT}/wwk" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	cd ${OCTEON_SDK_ROOT}
	source ./env-setup OCTEON_CN50XX
	echo "export OCTEON_CPPFLAGS_GLOBAL_ADD=${OCTEON_CPPFLAGS_GLOBAL_ADD}" >> ${DOT_CFG}
	echo "export OCTEON_MODEL=${OCTEON_MODEL}" >> ${DOT_CFG}
	echo "export OCTEON_ROOT=${OCTEON_ROOT}" >> ${DOT_CFG}
	if [ "${CVM_3602_GCC_PATH}" == "" ]
	then 
		echo "export PATH=${PATH}" >> ${DOT_CFG}
	else
		echo "export PATH=${CVM_3602_GCC_PATH}:${PATH}" >> ${DOT_CFG}
	fi
fi

if [ "${FAINT_PLATFORM}" == "5602" ]
then
	echo "" >> ${DOT_CFG}
	echo "export GCC_INCDIR=${CVM_5602_GCC_INCDIR}"  >> ${DOT_CFG}
	echo "export GCC_LIBDIR=${CVM_5602_GCC_LIBDIR}"  >> ${DOT_CFG}
	echo "export IMG_FS_ROOT=${CVM_5602_IMG_FS_ROOT}"  >> ${DOT_CFG}
	echo "export IMG_MK_ROOT=${CVM_5602_IMG_MK_ROOT}"  >> ${DOT_CFG}
	echo "export IMG_MK_TARGET=${CVM_5602_IMG_MK_TARGET}"  >> ${DOT_CFG}
	echo "export IMG_MK_OUTPUT=${CVM_5602_IMG_MK_OUTPUT}"  >> ${DOT_CFG}
	echo "" >> ${DOT_CFG}
	echo "export OCTEON_SDK_ROOT=${CVM_5602_OCTEON_SDK_ROOT}"  >> ${DOT_CFG}
	echo "export CAVIUM_SRC_ROOT=${CVM_5602_CAVIUM_SRC_ROOT}" >> ${DOT_CFG}
	echo "export CLOUD_PRJ_ROOT=`pwd`" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	echo "export LINUX_KERNEL=${CVM_5602_LINUX_KERNEL}" >> ${DOT_CFG}
	echo "export LINUX_SRC=${CVM_5602_LINUX_SRC}" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	if [ "${CVM_5602_GCC_PATH}" == "" ]
	then 
		echo "export PATH=${PATH}" >> ${DOT_CFG}
	else
		echo "export PATH=${CVM_5602_GCC_PATH}:${PATH}" >> ${DOT_CFG}
	fi
fi

if [ "${FAINT_PLATFORM}" == "marvell" ]
then
	echo "" >> ${DOT_CFG}
	echo "export GCC_INCDIR=${MV_88DE3010_GCC_INCDIR}"  >> ${DOT_CFG}
	echo "export GCC_LIBDIR=${MV_88DE3010_GCC_LIBDIR}"  >> ${DOT_CFG}
	echo "export IMG_FS_ROOT=${MV_88DE3010_IMG_FS_ROOT}"  >> ${DOT_CFG}
	echo "export IMG_MK_ROOT=${MV_88DE3010_IMG_MK_ROOT}"  >> ${DOT_CFG}
	echo "export IMG_MK_TARGET=${MV_88DE3010_IMG_MK_TARGET}"  >> ${DOT_CFG}
	echo "export IMG_MK_OUTPUT=${MV_88DE3010_IMG_MK_OUTPUT}"  >> ${DOT_CFG}
	echo "" >> ${DOT_CFG}
	echo "export OCTEON_SDK_ROOT=${MV_88DE3010_OCTEON_SDK_ROOT}"  >> ${DOT_CFG}
	echo "export CAVIUM_SRC_ROOT=${MV_88DE3010_CAVIUM_SRC_ROOT}" >> ${DOT_CFG}
	echo "export CLOUD_PRJ_ROOT=`pwd`" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	echo "export LINUX_KERNEL=${MV_88DE3010_LINUX_KERNEL}" >> ${DOT_CFG}
	echo "export LINUX_SRC=${MV_88DE3010_LINUX_SRC}" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	if [ "${MV_88DE3010_GCC_PATH}" == "" ]
	then 
		echo "export PATH=${PATH}" >> ${DOT_CFG}
	else
		echo "export PATH=${MV_88DE3010_GCC_PATH}:${PATH}" >> ${DOT_CFG}
	fi
fi

if [ "${FAINT_PLATFORM}" == "x86" ]
then
	echo "" >> ${DOT_CFG}
	echo "export GCC_INCDIR=${X86_GCC_INCDIR}"  >> ${DOT_CFG}
	echo "export GCC_LIBDIR=${X86_GCC_LIBDIR}"  >> ${DOT_CFG}
	echo "export IMG_FS_ROOT=${X86_IMG_FS_ROOT}"  >> ${DOT_CFG}
	echo "export IMG_MK_ROOT=${X86_IMG_MK_ROOT}"  >> ${DOT_CFG}
	echo "export IMG_MK_TARGET=${X86_IMG_MK_TARGET}"  >> ${DOT_CFG}
	echo "export IMG_MK_OUTPUT=${X86_IMG_MK_OUTPUT}"  >> ${DOT_CFG}
	echo "" >> ${DOT_CFG}
	echo "export OCTEON_SDK_ROOT=${X86_OCTEON_SDK_ROOT}"  >> ${DOT_CFG}
	echo "export CAVIUM_SRC_ROOT=${X86_CAVIUM_SRC_ROOT}" >> ${DOT_CFG}
	echo "export CLOUD_PRJ_ROOT=`pwd`" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	echo "export LINUX_KERNEL=${X86_LINUX_KERNEL}" >> ${DOT_CFG}
	echo "export LINUX_SRC=${X86_LINUX_SRC}" >> ${DOT_CFG}

	echo "" >> ${DOT_CFG}
	if [ "${X86_GCC_PATH}" == "" ]
	then 
		echo "export PATH=${PATH}" >> ${DOT_CFG}
	else
		echo "export PATH=${X86_GCC_PATH}:${PATH}" >> ${DOT_CFG}
	fi
fi

cat ${DOT_CFG}

