include $(CLOUD_PRJ_ROOT)/.configure

ifeq ($(FAINT_DEBUG),yes)
	CFLAGS += -g3
else
	CFLAGS += -O3
endif

CFLAGS += $(DEFINES) $(INCDIR)
LDFLAGS += $(LIBS)

MAKE += CC="$(CC)" AR="$(AR)" LD="$(LD)"

PATH := $(GCC_PATH):$(PATH)
