# Note: Automatically generated by kfg, do not edit.

export BKM_PRJ_ROOT := $(CURDIR)
export BKM_PLATFORM := 'x86.default'
export BKM_BUILD := 'alpine'


-include Makefile.defs
.PHONY: all clean install uninstall info renew

#########################################################################
## alpine
#
.PHONY: alpine.all
all: alpine.all
alpine.all:
	make -C /home/auv/eoe/woself/libhilda/SRCS/alpine all

.PHONY: alpine.clean
clean: alpine.clean
alpine.clean:
	make -C /home/auv/eoe/woself/libhilda/SRCS/alpine clean

.PHONY: alpine.install
install: alpine.install
alpine.install:
	make -C /home/auv/eoe/woself/libhilda/SRCS/alpine install

.PHONY: alpine.uninstall
uninstall: alpine.uninstall
alpine.uninstall:
	make -C /home/auv/eoe/woself/libhilda/SRCS/alpine uninstall

#########################################################################
## Information
#
info:
	@echo '    ALL PLATFORMS : 7231.default x86.default'
	@echo ' CURRENT PLATFORM : x86.default'
	@echo ''
	@echo '       ALL BUILDS : core test alpine'
	@echo '    CURRENT BUILD : alpine'
	@echo '             SRCS : alpine'

#########################################################################
## re-generate this Makefile
#
renew:
	@python kfg -b 'alpine' -p 'x86.default'
	@python kfg -d