# Note: Automatically generated by kfg, do not edit.

export BKM_PRJ_ROOT := $(CURDIR)
export BKM_PLATFORM := 'x86.default'
export BKM_BUILD := 'core'


-include Makefile.defs
.PHONY: all clean install uninstall info renew

#########################################################################
## core
#
.PHONY: core.all
all: core.all
core.all:
	make -C /home/auv/eoe/woself/libhilda/SRCS/core all

.PHONY: core.clean
clean: core.clean
core.clean:
	make -C /home/auv/eoe/woself/libhilda/SRCS/core clean


.PHONY: include.install
include.install:
	install -v ./inc/hilda/* /usr/include/hilda

.PHONY: core.install
install: core.install include.install
core.install:
	make -C /home/auv/eoe/woself/libhilda/SRCS/core install

.PHONY: core.uninstall
uninstall: core.uninstall
core.uninstall:
	make -C /home/auv/eoe/woself/libhilda/SRCS/core uninstall

#########################################################################
## Information
#
info:
	@echo '    ALL PLATFORMS : 7231.default x86.default'
	@echo ' CURRENT PLATFORM : x86.default'
	@echo ''
	@echo '       ALL BUILDS : core test alpine'
	@echo '    CURRENT BUILD : core'
	@echo '             SRCS : core'

#########################################################################
## re-generate this Makefile
#
renew:
	@python kfg -b 'core' -p 'x86.default'
	@python kfg -d
